### ISSUE TITLE
audio issue in suspended mode

### ISSUE THREAD

**Issue by xpdef** [thesofproject/sof-bin#153]
so whenever i press suspend and open my laptop back up, the sound is gone, the sliders and headphones are detected, but the sound doesnt appear

This is the command i used for installation:
`sudo ./install.sh v2.2.x/v2.2`
i dont need help asap, but it is pretty annoying

UPDATE:
**I rebooted my laptop and right after it entered verbose i heard the volume beep**

**Comment by marc-hb** [comment]
Hi @xpdef . As you could have guessed from the close to zero number of issues here, this isn't the right place to report actual audio issues. Don't worry, you're far from the first one which is why I just wrote this new template:
- https://github.com/thesofproject/sof-bin/pull/154/files

Please take a look at it. Feedback welcome!

Wherever your issue should be reported, a LOT more information is going to be required for any volunteer to help you. Have you also tried to contact the vendor of your PC? (assuming your model wasn't designed to run Windows)
